/**
 * E-Commerce Jewelry Store API
 * REST API for a jewelry e-commerce application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GemShape } from './gemShape';
import { GemSize } from './gemSize';
import { JewelryType } from './jewelryType';

export class ItemBaseInput {
    'gem_size': GemSize;
    'gem_shape': GemShape;
    /**
    * Name of the gemstone.
    */
    'gem_name': string;
    'jewelry_type': JewelryType;
    /**
    * Price of the item.
    */
    'price': number;
    /**
    * Indicates if the item is currently in stock.
    */
    'in_stock'?: boolean = true;
    /**
    * URL of the item\'s image.
    */
    'img_url': string;
    /**
    * Indicates if the item is featured.
    */
    'is_featured'?: boolean = false;
    /**
    * Indicates if the item is hidden from public view.
    */
    'is_hidden'?: boolean = false;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "gem_size",
            "baseName": "gem_size",
            "type": "GemSize"
        },
        {
            "name": "gem_shape",
            "baseName": "gem_shape",
            "type": "GemShape"
        },
        {
            "name": "gem_name",
            "baseName": "gem_name",
            "type": "string"
        },
        {
            "name": "jewelry_type",
            "baseName": "jewelry_type",
            "type": "JewelryType"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number"
        },
        {
            "name": "in_stock",
            "baseName": "in_stock",
            "type": "boolean"
        },
        {
            "name": "img_url",
            "baseName": "img_url",
            "type": "string"
        },
        {
            "name": "is_featured",
            "baseName": "is_featured",
            "type": "boolean"
        },
        {
            "name": "is_hidden",
            "baseName": "is_hidden",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return ItemBaseInput.attributeTypeMap;
    }
}

export namespace ItemBaseInput {
}
