/**
 * E-Commerce Jewelry Store API
 * REST API for a jewelry e-commerce application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { OrderItem } from './orderItem';
import { OrderStatus } from './orderStatus';
import { UserAddress } from './userAddress';

export class Order {
    'id'?: number;
    'user_id'?: number;
    'status'?: OrderStatus;
    'total'?: number;
    'shipping_address'?: UserAddress;
    'created_at'?: Date;
    'updated_at'?: Date;
    'items'?: Array<OrderItem>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "user_id",
            "baseName": "user_id",
            "type": "number"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "OrderStatus"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number"
        },
        {
            "name": "shipping_address",
            "baseName": "shipping_address",
            "type": "UserAddress"
        },
        {
            "name": "created_at",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "updated_at",
            "baseName": "updated_at",
            "type": "Date"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<OrderItem>"
        }    ];

    static getAttributeTypeMap() {
        return Order.attributeTypeMap;
    }
}

export namespace Order {
}
