/**
 * E-Commerce Jewelry Store API
 * REST API for a jewelry e-commerce application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class OrderItemItemSnapshot {
    'item_name'?: string;
    'gem_name'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "item_name",
            "baseName": "item_name",
            "type": "string"
        },
        {
            "name": "gem_name",
            "baseName": "gem_name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return OrderItemItemSnapshot.attributeTypeMap;
    }
}

