/**
 * E-Commerce Jewelry Store API
 * REST API for a jewelry e-commerce application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { OrderItemItemSnapshot } from './orderItemItemSnapshot';

export class OrderItem {
    'item_id': number;
    'quantity': number;
    'price_at_purchase': number;
    'item_name'?: string;
    'item_snapshot'?: OrderItemItemSnapshot;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "item_id",
            "baseName": "item_id",
            "type": "number"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        },
        {
            "name": "price_at_purchase",
            "baseName": "price_at_purchase",
            "type": "number"
        },
        {
            "name": "item_name",
            "baseName": "item_name",
            "type": "string"
        },
        {
            "name": "item_snapshot",
            "baseName": "item_snapshot",
            "type": "OrderItemItemSnapshot"
        }    ];

    static getAttributeTypeMap() {
        return OrderItem.attributeTypeMap;
    }
}

