/**
 * E-Commerce Jewelry Store API
 * REST API for a jewelry e-commerce application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UserAddress } from './userAddress';

export class PartialUserUpdate {
    'username'?: string;
    'email'?: string;
    'address'?: UserAddress;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "username",
            "baseName": "username",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "UserAddress"
        }    ];

    static getAttributeTypeMap() {
        return PartialUserUpdate.attributeTypeMap;
    }
}

