/**
 * E-Commerce Jewelry Store API
 * REST API for a jewelry e-commerce application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Colors } from './colors';
import { GemShape } from './gemShape';
import { GemSize } from './gemSize';
import { JewelryType } from './jewelryType';

export class PartialItemUpdate {
    'gem_size'?: GemSize;
    'gem_shape'?: GemShape;
    'gem_name'?: string;
    'jewelry_type'?: JewelryType;
    'price'?: number;
    'in_stock'?: boolean;
    'img_url'?: string;
    'is_featured'?: boolean;
    'is_hidden'?: boolean;
    'ring_size'?: number;
    'ring_color'?: Colors;
    'ring_style'?: string;
    'necklace_length'?: number;
    'necklace_color'?: Colors;
    'necklace_style'?: string;
    'earring_size'?: number;
    'earring_color'?: Colors;
    'earring_style'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "gem_size",
            "baseName": "gem_size",
            "type": "GemSize"
        },
        {
            "name": "gem_shape",
            "baseName": "gem_shape",
            "type": "GemShape"
        },
        {
            "name": "gem_name",
            "baseName": "gem_name",
            "type": "string"
        },
        {
            "name": "jewelry_type",
            "baseName": "jewelry_type",
            "type": "JewelryType"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number"
        },
        {
            "name": "in_stock",
            "baseName": "in_stock",
            "type": "boolean"
        },
        {
            "name": "img_url",
            "baseName": "img_url",
            "type": "string"
        },
        {
            "name": "is_featured",
            "baseName": "is_featured",
            "type": "boolean"
        },
        {
            "name": "is_hidden",
            "baseName": "is_hidden",
            "type": "boolean"
        },
        {
            "name": "ring_size",
            "baseName": "ring_size",
            "type": "number"
        },
        {
            "name": "ring_color",
            "baseName": "ring_color",
            "type": "Colors"
        },
        {
            "name": "ring_style",
            "baseName": "ring_style",
            "type": "string"
        },
        {
            "name": "necklace_length",
            "baseName": "necklace_length",
            "type": "number"
        },
        {
            "name": "necklace_color",
            "baseName": "necklace_color",
            "type": "Colors"
        },
        {
            "name": "necklace_style",
            "baseName": "necklace_style",
            "type": "string"
        },
        {
            "name": "earring_size",
            "baseName": "earring_size",
            "type": "number"
        },
        {
            "name": "earring_color",
            "baseName": "earring_color",
            "type": "Colors"
        },
        {
            "name": "earring_style",
            "baseName": "earring_style",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PartialItemUpdate.attributeTypeMap;
    }
}

export namespace PartialItemUpdate {
}
