/**
 * E-Commerce Jewelry Store API
 * REST API for a jewelry e-commerce application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Colors } from './colors';

export class RingDetails {
    /**
    * Standard US ring size.
    */
    'ring_size': number;
    'ring_color': Colors;
    /**
    * Specific style of the ring (e.g., Solitaire, Halo).
    */
    'ring_style': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ring_size",
            "baseName": "ring_size",
            "type": "number"
        },
        {
            "name": "ring_color",
            "baseName": "ring_color",
            "type": "Colors"
        },
        {
            "name": "ring_style",
            "baseName": "ring_style",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RingDetails.attributeTypeMap;
    }
}

export namespace RingDetails {
}
