/**
 * E-Commerce Jewelry Store API
 * REST API for a jewelry e-commerce application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UserAddress } from './userAddress';

export class User {
    'id': number;
    'username': string;
    'email': string;
    /**
    * User role (e.g., \'customer\', \'admin\')
    */
    'role': string;
    'created_at': Date;
    'updated_at'?: Date;
    'address'?: UserAddress;
    'last_login'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "string"
        },
        {
            "name": "created_at",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "updated_at",
            "baseName": "updated_at",
            "type": "Date"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "UserAddress"
        },
        {
            "name": "last_login",
            "baseName": "last_login",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return User.attributeTypeMap;
    }
}

