/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Colors = "gold" | "silver";

export type GemShapes = "chaa" | "choo" | "flippy" | "floopy";

export type GemSizes = "chonki" | "midi" | "mini" | "tini";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type JewelryTypes = "earring" | "necklace" | "ring";

export type Numeric = ColumnType<string, number | string, number | string>;

export type OrderStatus = "cancelled" | "pending" | "returned" | "shipped";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRoles = "admin" | "customer";

export interface Earring {
  earring_color: Colors | null;
  earring_id: number;
  earring_size: Numeric | null;
  earring_style: string | null;
}

export interface Items {
  created_at: Generated<Timestamp>;
  gem_name: string;
  gem_shape: GemShapes | null;
  gem_size: GemSizes | null;
  id: Generated<number>;
  img_url: string | null;
  in_stock: boolean;
  is_featured: boolean | null;
  is_hidden: boolean | null;
  item_name: string | null;
  jewelry_type: JewelryTypes | null;
  price: Numeric;
  updated_at: Timestamp | null;
}

export interface ItemsTags {
  item_id: number;
  tag_id: number;
}

export interface Necklace {
  necklace_color: Colors | null;
  necklace_id: number;
  necklace_length: Numeric | null;
  necklace_style: string | null;
}

export interface Orders {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  shipping_address: string;
  status: Generated<OrderStatus | null>;
  total: Numeric;
  user_id: number | null;
}

export interface OrdersItems {
  item_id: number;
  order_id: number;
  price_at_purchase: Numeric | null;
}

export interface Reviews {
  created_at: Timestamp | null;
  id: Generated<number>;
  rating: number | null;
  review: string;
  user_id: number | null;
}

export interface Ring {
  ring_color: Colors | null;
  ring_id: number;
  ring_size: Numeric | null;
  ring_style: string | null;
}

export interface Tags {
  id: Generated<number>;
  tag: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  is_active: Generated<boolean | null>;
  last_login: Timestamp | null;
  password: string;
  password_reset_expires: Timestamp | null;
  password_reset_token: string | null;
  user_role: UserRoles;
  username: string;
}

export interface DB {
  earring: Earring;
  items: Items;
  items_tags: ItemsTags;
  necklace: Necklace;
  orders: Orders;
  orders_items: OrdersItems;
  reviews: Reviews;
  ring: Ring;
  tags: Tags;
  users: Users;
}
