/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ControllerType = "app" | "remote";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type ModuleSize = "large" | "medium" | "small";

export type Numeric = ColumnType<string, number | string, number | string>;

export type OrderStatus = "cancelled" | "delivered" | "pending" | "processing" | "shipped";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "customer" | "manager";

export interface Accessories {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  size: ModuleSize | null;
  updated_at: Timestamp | null;
}

export interface CartItems {
  created_at: Generated<Timestamp | null>;
  id: Generated<number>;
  item_id: number | null;
  quantity: number;
  updated_at: Timestamp | null;
  user_id: number | null;
}

export interface Items {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  img_url: string | null;
  in_stock: boolean;
  is_featured: boolean | null;
  is_hidden: boolean | null;
  item_name: string | null;
  price: Numeric;
  updated_at: Timestamp | null;
}

export interface ItemsTags {
  item_id: number;
  tag_id: number;
}

export interface Modules {
  controller: ControllerType;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  size: ModuleSize;
  updated_at: Timestamp | null;
}

export interface ModulesItems {
  item_id: number;
  module_id: number;
}

export interface Orders {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  shipping_address: string;
  status: Generated<OrderStatus | null>;
  total: Numeric;
  updated_at: Timestamp | null;
  user_id: number | null;
}

export interface Reviews {
  created_at: Timestamp | null;
  id: Generated<number>;
  rating: number | null;
  review: string;
  updated_at: Timestamp | null;
  user_id: number | null;
}

export interface Tags {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  updated_at: Timestamp | null;
}

export interface UserAddresses {
  city: string;
  country: string;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  phone: string | null;
  street: string;
  updated_at: Timestamp | null;
  user_id: number;
  zip: string | null;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  is_active: Generated<boolean | null>;
  last_login: Timestamp | null;
  password: string;
  password_reset_expires: Timestamp | null;
  password_reset_token: string | null;
  updated_at: Generated<Timestamp>;
  user_role: UserRole;
  username: string;
}

export interface DB {
  accessories: Accessories;
  cart_items: CartItems;
  items: Items;
  items_tags: ItemsTags;
  modules: Modules;
  modules_items: ModulesItems;
  orders: Orders;
  reviews: Reviews;
  tags: Tags;
  user_addresses: UserAddresses;
  users: Users;
}
