/**
 * E-Commerce Jewelry Store API
 * REST API for a jewelry e-commerce application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class ErrorResponse {
    /**
    * Application-specific error code (optional).
    */
    'code'?: string;
    /**
    * Human-readable description of the error.
    */
    'message': string;
    'details'?: { [key: string]: any; };
}

