/**
 * E-Commerce Jewelry Store API
 * REST API for a jewelry e-commerce application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Item } from './item';

export class ItemsGet200Response {
    /**
    * Total number of items matching the query.
    */
    'total_count'?: number;
    'items'?: Array<Item>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "total_count",
            "baseName": "total_count",
            "type": "number"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<Item>"
        }    ];

    static getAttributeTypeMap() {
        return ItemsGet200Response.attributeTypeMap;
    }
}

