/**
 * E-Commerce Jewelry Store API
 * REST API for a jewelry e-commerce application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Colors } from './colors.js';
import { GemShape } from './gemShape.js';
import { GemSize } from './gemSize.js';
import { ItemEarring } from './itemEarring.js';
import { ItemNecklace } from './itemNecklace.js';
import { ItemRing } from './itemRing.js';
import { JewelryType } from './jewelryType.js';

export class Item {
    'id'?: number;
    'gem_size': GemSize;
    'gem_shape': GemShape;
    'gem_name': string;
    'jewelry_type': JewelryType;
    /**
    * Auto-generated as `gem_name + \" \" + jewelry_type` by the server.
    */
    'item_name'?: string;
    'price': number;
    'in_stock': boolean;
    'img_url': string;
    /**
    * Timestamp when the item was created.
    */
    'created_at'?: Date;
    /**
    * Timestamp when the item was updated.
    */
    'updated_at'?: Date;
    'is_featured': boolean;
    'is_hidden': boolean;
    /**
    * Standard ring size.
    */
    'ring_size': number;
    'ring_color': Colors;
    /**
    * Specific style of the ring (e.g., Solitaire, Halo).
    */
    'ring_style': string;
    /**
    * Length of the necklace chain in cm or inches.
    */
    'necklace_length': number;
    'necklace_color': Colors;
    /**
    * Specific style of the necklace (e.g., Pendant, Choker).
    */
    'necklace_style': string;
    /**
    * Size dimension (e.g., diameter, length).
    */
    'earring_size': number;
    'earring_color': Colors;
    /**
    * Specific style of the earring (e.g., Stud, Hoop, Dangle).
    */
    'earring_style': string;
}

export namespace Item {
}
