/**
 * E-Commerce Jewelry Store API
 * REST API for a jewelry e-commerce application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Item } from './item.js';

export class ItemsGet200Response {
    /**
    * Total number of items matching the query.
    */
    'total_count'?: number;
    'items'?: Array<Item>;
}

