/**
 * E-Commerce Jewelry Store API
 * REST API for a jewelry e-commerce application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Colors } from './colors';

export class NecklaceDetails {
    /**
    * Length of the necklace chain in cm or inches.
    */
    'necklace_length': number;
    'necklace_color': Colors;
    /**
    * Specific style of the necklace (e.g., Pendant, Choker).
    */
    'necklace_style': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "necklace_length",
            "baseName": "necklace_length",
            "type": "number"
        },
        {
            "name": "necklace_color",
            "baseName": "necklace_color",
            "type": "Colors"
        },
        {
            "name": "necklace_style",
            "baseName": "necklace_style",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return NecklaceDetails.attributeTypeMap;
    }
}

export namespace NecklaceDetails {
}
