/**
 * E-Commerce Jewelry Store API
 * REST API for a jewelry e-commerce application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Colors } from './colors.js';

export class NecklaceDetails {
    /**
    * Length of the necklace chain in cm or inches.
    */
    'necklace_length': number;
    'necklace_color': Colors;
    /**
    * Specific style of the necklace (e.g., Pendant, Choker).
    */
    'necklace_style': string;
}

export namespace NecklaceDetails {
}
