/**
 * E-Commerce Jewelry Store API
 * REST API for a jewelry e-commerce application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Colors } from './colors.js';
import { GemShape } from './gemShape.js';
import { GemSize } from './gemSize.js';
import { JewelryType } from './jewelryType.js';

export class NewItemInput {
    'gem_size': GemSize;
    'gem_shape': GemShape;
    'gem_name': string;
    'jewelry_type': JewelryType;
    'price': number;
    'in_stock': boolean;
    'img_url': string;
    'is_featured': boolean;
    'is_hidden': boolean;
    /**
    * Required if jewelry_type is \'ring\'.
    */
    'ring_size'?: number;
    /**
    * Required if jewelry_type is \'ring\'.
    */
    'ring_color'?: Colors;
}

export namespace NewItemInput {
}
