/**
 * E-Commerce Jewelry Store API
 * REST API for a jewelry e-commerce application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderItem } from './orderItem';
import { OrderStatus } from './orderStatus';
import { UserAddress } from './userAddress';

export class Order {
    'id'?: number;
    'user_id'?: number;
    'status'?: OrderStatus;
    'total'?: number;
    'shipping_address'?: UserAddress;
    'created_at'?: Date;
    'updated_at'?: Date;
    'items'?: Array<OrderItem>;
}

export namespace Order {
}
