/**
 * E-Commerce Jewelry Store API
 * REST API for a jewelry e-commerce application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderItemItemSnapshot } from './orderItemItemSnapshot.js';

export class OrderItem {
    'item_id': number;
    'quantity': number;
    'price_at_purchase': number;
    'item_name'?: string;
    'item_snapshot'?: OrderItemItemSnapshot;
}

