/**
 * E-Commerce Jewelry Store API
 * REST API for a jewelry e-commerce application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Colors } from './colors';
import { GemShape } from './gemShape';
import { GemSize } from './gemSize';
import { JewelryType } from './jewelryType';

export class PartialItemUpdate {
    'gem_size'?: GemSize;
    'gem_shape'?: GemShape;
    'gem_name'?: string;
    'jewelry_type'?: JewelryType;
    'price'?: number;
    'in_stock'?: boolean;
    'img_url'?: string;
    'is_featured'?: boolean;
    'is_hidden'?: boolean;
    'ring_size'?: number;
    'ring_color'?: Colors;
}

export namespace PartialItemUpdate {
}
