/**
 * E-Commerce Jewelry Store API
 * REST API for a jewelry e-commerce application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Colors } from './colors';
import { GemShape } from './gemShape';
import { GemSize } from './gemSize';
import { JewelryType } from './jewelryType';

export class ItemEarring {
    'id'?: number;
    'gem_size': GemSize;
    'gem_shape': GemShape;
    'gem_name': string;
    'jewelry_type': JewelryType;
    /**
    * Auto-generated as `gem_name + \" \" + jewelry_type` by the server.
    */
    'item_name'?: string;
    'price': number;
    'in_stock': boolean;
    'img_url': string;
    /**
    * Timestamp when the item was created.
    */
    'created_at'?: Date;
    /**
    * Timestamp when the item was updated.
    */
    'updated_at'?: Date;
    'is_featured': boolean;
    'is_hidden': boolean;
    /**
    * Size dimension (e.g., diameter, length).
    */
    'earring_size': number;
    'earring_color': Colors;
    /**
    * Specific style of the earring (e.g., Stud, Hoop, Dangle).
    */
    'earring_style': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "gem_size",
            "baseName": "gem_size",
            "type": "GemSize"
        },
        {
            "name": "gem_shape",
            "baseName": "gem_shape",
            "type": "GemShape"
        },
        {
            "name": "gem_name",
            "baseName": "gem_name",
            "type": "string"
        },
        {
            "name": "jewelry_type",
            "baseName": "jewelry_type",
            "type": "JewelryType"
        },
        {
            "name": "item_name",
            "baseName": "item_name",
            "type": "string"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number"
        },
        {
            "name": "in_stock",
            "baseName": "in_stock",
            "type": "boolean"
        },
        {
            "name": "img_url",
            "baseName": "img_url",
            "type": "string"
        },
        {
            "name": "created_at",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "updated_at",
            "baseName": "updated_at",
            "type": "Date"
        },
        {
            "name": "is_featured",
            "baseName": "is_featured",
            "type": "boolean"
        },
        {
            "name": "is_hidden",
            "baseName": "is_hidden",
            "type": "boolean"
        },
        {
            "name": "earring_size",
            "baseName": "earring_size",
            "type": "number"
        },
        {
            "name": "earring_color",
            "baseName": "earring_color",
            "type": "Colors"
        },
        {
            "name": "earring_style",
            "baseName": "earring_style",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ItemEarring.attributeTypeMap;
    }
}

export namespace ItemEarring {
}
