/**
 * E-Commerce Jewelry Store API
 * REST API for a jewelry e-commerce application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Colors } from './colors';
import { GemShape } from './gemShape';
import { GemSize } from './gemSize';
import { JewelryType } from './jewelryType';

export class NewItemInput {
    'gem_size': GemSize;
    'gem_shape': GemShape;
    'gem_name': string;
    'jewelry_type': JewelryType;
    'price': number;
    'in_stock': boolean;
    'img_url': string;
    'is_featured': boolean;
    'is_hidden': boolean;
    /**
    * Required if jewelry_type is \'ring\'.
    */
    'ring_size'?: number;
    /**
    * Required if jewelry_type is \'ring\'.
    */
    'ring_color'?: Colors;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "gem_size",
            "baseName": "gem_size",
            "type": "GemSize"
        },
        {
            "name": "gem_shape",
            "baseName": "gem_shape",
            "type": "GemShape"
        },
        {
            "name": "gem_name",
            "baseName": "gem_name",
            "type": "string"
        },
        {
            "name": "jewelry_type",
            "baseName": "jewelry_type",
            "type": "JewelryType"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number"
        },
        {
            "name": "in_stock",
            "baseName": "in_stock",
            "type": "boolean"
        },
        {
            "name": "img_url",
            "baseName": "img_url",
            "type": "string"
        },
        {
            "name": "is_featured",
            "baseName": "is_featured",
            "type": "boolean"
        },
        {
            "name": "is_hidden",
            "baseName": "is_hidden",
            "type": "boolean"
        },
        {
            "name": "ring_size",
            "baseName": "ring_size",
            "type": "number"
        },
        {
            "name": "ring_color",
            "baseName": "ring_color",
            "type": "Colors"
        }    ];

    static getAttributeTypeMap() {
        return NewItemInput.attributeTypeMap;
    }
}

export namespace NewItemInput {
}
