/**
 * E-Commerce Jewelry Store API
 * REST API for a jewelry e-commerce application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderItemInput } from './orderItemInput';
import { UserAddress } from './userAddress';

export class NewOrder {
    'shipping_address': UserAddress;
    'items': Array<OrderItemInput>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "shipping_address",
            "baseName": "shipping_address",
            "type": "UserAddress"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<OrderItemInput>"
        }    ];

    static getAttributeTypeMap() {
        return NewOrder.attributeTypeMap;
    }
}

